### ISSUE TITLE
Script not detecting payments from wallet divisions

### ISSUE THREAD

**Issue by Bloodspike** [bahrmichael/eve-pos-taxer#12]
A client used a wallet division (no.2) instead of the Master Wallet to make the payment. It was not detected by the app. The corp ID is 98467525 and the transaction took place o
![image](https://cloud.githubusercontent.com/assets/25075509/21882641/0ea8d6fc-d8b4-11e6-803c-0699a97d67fd.png)
n 2017-01-02 05:14:32

**Comment by bahrmichael** [comment]
The app does not parse wallet divisions yet. I found the transaction in a different wallet.

`<row date="2017-01-02 05:14:32" ... amount="-272000000.00" ... reason="DESC: Moon tax&#xA;" ... />`

Implementation note: Add a loop where the parameter accountKey is [1000 to 1006](http://eveonline-third-party-documentation.readthedocs.io/en/latest/xmlapi/corporation/corp_accountbalance.html).

**Comment by bahrmichael** [comment]
To catch old transactions, set the rowCount to 2560 (max).
